### ISSUE TITLE
docker inside docker

### ISSUE THREAD

**Issue by tollkin71** [jgillula/paperless-ngx-postprocessor#1]

**Comment by tollkin71** [comment]
I am using this file to create paperless-ngx, but I am not able to run the setup_venv.sh script

version: "3.6"
services:
  broker:
    image: redis
    restart: always
    volumes:
      - /volume2/docker/paperedis:/data

  db:
    image: postgres
    restart: always
    volumes:
      - /volume2/docker/paperdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: always
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8777:8000
    volumes:
      - /volume2/share2/paperless/data:/usr/src/paperless/data
      - /volume2/share2/paperless/media:/usr/src/paperless/media
      - /volume2/share2/paperless/export:/usr/src/paperless/export
      - /volume2/share2/paperless/consume:/usr/src/paperless/consume
      - /volume2/share2/paperless/script/paperless-ngx-postprocessor:/usr/src/paperless-ngx-postprocessor
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1026
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: admin
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS WEBSERVER WORKERS: 4
      PAPERLESS THREADS PER WORKER: 4
      PAPERLESS_POST_CONSUME_SCRIPT: /usr/src/paperless-ngx-postprocessor/post_consume_script.sh
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000/forms/libreoffice/convert#
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      
  gotenberg:
      container_name: paperless-gotenberg
      image: gotenberg/gotenberg:7
      restart: unless-stopped
      environment:
        CHROMIUM_DISABLE_ROUTES: 1


  tika:
    container_name: paperless-tika
    image: apache/tika:2.3.0
    restart: unless-stopped

**Comment by jgillula** [comment]
Hi there! I assume this means you got things working OK? Is there anything I can do to make the instructions more clear?

**Comment by tollkin71** [comment]
Good morning,
thx for coming back. For me this line is/was not working:
docker-compose exec -u paperless webserver /usr/src/paperless-ngx-postprocessor/setup_venv.sh
My way around was, to copy the content of the script and to run it directly inside a shell inside the docker container. But the script has not absolut path values, so it was critical to find the right directory to start.
Thx in advance. Now everything works fine

**Comment by jgillula** [comment]
Just to double-check, you were running that entire line from the host, not going into the docker container first and then trying to run that line, right?

Can you share what the error(s) was?

**Comment by jgillula** [comment]
I'm going to go ahead and close this since it hasn't had any response for a couple months. Please do reopen a new issue if you're still having trouble.
