### ISSUE TITLE
Do you provide customisation of Paperless-Ngx?

### ISSUE THREAD

**Issue by willieloo** [jgillula/paperless-ngx-postprocessor#22]
Hi ,

Do you install and customise paperless-ngx so that once we upload the files, it will auto rename them based on their content, e.g., invoice number?

![python-rename](https://github.com/jgillula/paperless-ngx-postprocessor/assets/77987159/00c5a088-bca2-4084-bef6-31f4300429a4)

**Comment by jgillula** [comment]
Yes, if you can extract the invoice number using a regular expression, you can use paperless-ngx-postprocessor to rename the file's title with that.
