### ISSUE TITLE
Use of custom fields?

### ISSUE THREAD

**Issue by apachler** [jgillula/paperless-ngx-postprocessor#23]
Is it possible to fill custom fields of documents with content extracted by rules?

**Comment by jgillula** [comment]
Not currently. Unfortunately I don't have the bandwidth to add this feature at the moment, although I'd be happy to accept a pull request if someone else could. I believe @hasechris was working on this (see #19), but I'm not sure if they finished.

**Comment by apachler** [comment]
Thanks for pointing out ...
