### ISSUE TITLE
Postprocessing gives errors if document doesn't have storage path, correspondent, or document type set

### ISSUE THREAD

**Issue by esmoyer** [jgillula/paperless-ngx-postprocessor#7]
I'm slowly figuring PaperlessNGX and this post-processing script out but I can't seem to figure out why when I manually run this script, the PaperlessNGX logs show this error: `[WARNING] [django.request] Not Found: /api/storage_paths/None/`

Not sure if I overlooked something, any insight that might point me in the right direction? Thanks!

**Comment by jgillula** [comment]
Do you have any documents that don't have a storage path set?

I don't think the code currently takes into account that storage path, correspondent, or document type could be set to none...

I think I can fix the bug, but I probably won't be able to get to it until this weekend.

**Comment by esmoyer** [comment]
Oh, wow. Yep, that was it. I know I overlooked something. For some reason I thought the storage path was set automatically. Set them manually and ran the script again and no errors. Thanks!

**Comment by jgillula** [comment]
I'm going to reopen this to track making the code more fault tolerant to missing storage paths, document types, and correspondents.
